"""Add genre to book

Revision ID: 8d844917cb33
Revises: dcf7523ec8c6
Create Date: 2025-06-12 18:14:29.391409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d844917cb33'
down_revision: Union[str, None] = 'dcf7523ec8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('genre', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_book_genre'), 'book', ['genre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_genre'), table_name='book')
    op.drop_column('book', 'genre')
    # ### end Alembic commands ###
